import { Link } from "react-router-dom";
import { useUIStore } from "../store/uiStore";
import { useTranslation } from "react-i18next";
import { useLoanSnapshot } from "../../features/loans/hooks/useLoanSnapshot";
import { useAuditTimeline } from "../../features/loans/hooks/useAuditTimeline";
import { loanPaths } from "../routes/paths";

function formatMoney(amount: number, currency: string) {
  try {
    return new Intl.NumberFormat(undefined, {
      style: "currency",
      currency,
      maximumFractionDigits: 0,
    }).format(amount);
  } catch {
    return `${currency} ${Math.round(amount).toLocaleString()}`;
  }
}

function exportLoanSummary(loanData: any, auditData: any[], loanId: string) {
  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    alert("Please allow pop-ups to export the summary");
    return;
  }

  const html = `
<!DOCTYPE html>
<html>
<head>
  <title>Loan Summary - ${loanId}</title>
  <style>
    @media print {
      @page {
        margin: 1.5cm;
      }
      body {
        margin: 0;
      }
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', sans-serif;
      line-height: 1.6;
      color: #1e293b;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }
    h1 {
      color: #0f172a;
      border-bottom: 3px solid #3b82f6;
      padding-bottom: 10px;
      margin-bottom: 30px;
    }
    h2 {
      color: #334155;
      margin-top: 30px;
      margin-bottom: 15px;
      font-size: 18px;
      border-bottom: 1px solid #e2e8f0;
      padding-bottom: 5px;
    }
    .info-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 15px;
      margin: 20px 0;
    }
    .info-card {
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 15px;
      background: #f8fafc;
    }
    .info-label {
      font-size: 12px;
      color: #64748b;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      margin-bottom: 5px;
    }
    .info-value {
      font-size: 18px;
      font-weight: 700;
      color: #0f172a;
    }
    .audit-timeline {
      margin: 20px 0;
    }
    .audit-item {
      margin-bottom: 15px;
      padding: 12px;
      border-left: 3px solid #3b82f6;
      background: #f8fafc;
      border-radius: 4px;
    }
    .audit-summary {
      font-weight: 600;
      color: #0f172a;
      margin-bottom: 5px;
    }
    .audit-meta {
      font-size: 12px;
      color: #64748b;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e2e8f0;
      font-size: 12px;
      color: #64748b;
      text-align: center;
    }
    @media print {
      .no-print {
        display: none;
      }
    }
  </style>
</head>
<body>
  <h1>Loan Summary Report</h1>
  
  <div class="info-grid">
    <div class="info-card">
      <div class="info-label">Loan ID</div>
      <div class="info-value">${loanId}</div>
    </div>
    <div class="info-card">
      <div class="info-label">Borrower</div>
      <div class="info-value">${loanData.borrower || "—"}</div>
    </div>
    <div class="info-card">
      <div class="info-label">Agent Bank</div>
      <div class="info-value">${loanData.agentBank || "—"}</div>
    </div>
    <div class="info-card">
      <div class="info-label">Status</div>
      <div class="info-value">${loanData.status || "—"}</div>
    </div>
    <div class="info-card">
      <div class="info-label">Facility Amount</div>
      <div class="info-value">${formatMoney(loanData.facilityAmount, loanData.currency)}</div>
    </div>
    <div class="info-card">
      <div class="info-label">Margin</div>
      <div class="info-value">${loanData.marginBps || 0} bps</div>
    </div>
    <div class="info-card">
      <div class="info-label">Covenants</div>
      <div class="info-value">${loanData.covenants || 0}</div>
    </div>
    <div class="info-card">
      <div class="info-label">ESG Clauses</div>
      <div class="info-value">${loanData.esgClauses || 0}</div>
    </div>
  </div>

  <div style="margin: 20px 0; padding: 12px; background: #f1f5f9; border-radius: 8px; font-size: 13px;">
    <strong>Last Updated:</strong> ${new Date(loanData.lastUpdatedAt).toLocaleString()}
  </div>

  <h2>Recent Audit Timeline</h2>
  <div class="audit-timeline">
    ${auditData.length > 0
      ? auditData
          .slice(0, 10)
          .map(
            (evt) => `
      <div class="audit-item">
        <div class="audit-summary">${evt.summary || "—"}</div>
        <div class="audit-meta">
          ${new Date(evt.timestamp).toLocaleString()} • ${evt.actor || "—"}
          ${evt.evidenceRef ? ` • ${evt.evidenceRef}` : ""}
        </div>
      </div>
    `
          )
          .join("")
      : "<div style='color: #64748b; font-style: italic;'>No audit events available</div>"}
  </div>

  <div class="footer">
    <p>Generated by LEXA Ledger on ${new Date().toLocaleString()}</p>
    <p>This is a system-generated summary. For detailed information, please refer to the full loan workspace.</p>
  </div>

  <script>
    window.onload = function() {
      setTimeout(function() {
        window.print();
      }, 250);
    };
  </script>
</body>
</html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
}

export function RightDrawer() {
  const { t } = useTranslation("common");
  const activeLoanId = useUIStore((s) => s.activeLoanId);
  const open = useUIStore((s) => s.rightDrawerOpen);
  const setOpen = useUIStore((s) => s.setRightDrawerOpen);

  const loanQ = useLoanSnapshot(activeLoanId);
  const auditQ = useAuditTimeline(activeLoanId);

  if (!open) {
    return <div style={{ padding: 16, color: "rgb(var(--muted))" }}>{t("drawer.noSelection")}</div>;
  }

  return (
    <div className="right-drawer no-print" style={{ height: "100%", display: "flex", flexDirection: "column" }}>
      <div
        style={{
          padding: 16,
          borderBottom: "1px solid rgb(var(--border))",
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
        }}
      >
        <div>
          <div style={{ fontWeight: 700 }}>{t("drawer.loanSnapshot")}</div>
          <div style={{ fontSize: 12, color: "rgb(var(--muted))" }}>{activeLoanId ?? "-"}</div>
        </div>
        <button
          onClick={() => setOpen(false)}
          style={{
            border: "1px solid rgb(var(--border))",
            borderRadius: 10,
            padding: "6px 10px",
            background: "rgb(var(--card))",
          }}
        >
          {t("close")}
        </button>
      </div>

      {/* Snapshot */}
      <div style={{ padding: 16 }}>
        {loanQ.isLoading ? (
          <div style={{ color: "rgb(var(--muted))" }}>Loading snapshot…</div>
        ) : loanQ.isError ? (
          <div style={{ color: "rgb(var(--danger))" }}>Failed to load snapshot</div>
        ) : loanQ.data ? (
          <>
            <div style={{ fontWeight: 700, marginBottom: 6 }}>{loanQ.data.borrower}</div>
            <div style={{ fontSize: 12, color: "rgb(var(--muted))", marginBottom: 12 }}>
              Agent: {loanQ.data.agentBank} • Status: {loanQ.data.status}
            </div>

            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>
              <div
                style={{
                  padding: 10,
                  borderRadius: 12,
                  border: "1px solid rgb(var(--border))",
                  background: "rgb(var(--bg))",
                }}
              >
                <div style={{ fontSize: 11, color: "rgb(var(--muted))" }}>Facility</div>
                <div style={{ fontWeight: 700 }}>
                  {formatMoney(loanQ.data.facilityAmount, loanQ.data.currency)}
                </div>
              </div>

              <div
                style={{
                  padding: 10,
                  borderRadius: 12,
                  border: "1px solid rgb(var(--border))",
                  background: "rgb(var(--bg))",
                }}
              >
                <div style={{ fontSize: 11, color: "rgb(var(--muted))" }}>Margin</div>
                <div style={{ fontWeight: 700 }}>{loanQ.data.marginBps} bps</div>
              </div>

              <div
                style={{
                  padding: 10,
                  borderRadius: 12,
                  border: "1px solid rgb(var(--border))",
                  background: "rgb(var(--bg))",
                }}
              >
                <div style={{ fontSize: 11, color: "rgb(var(--muted))" }}>Covenants</div>
                <div style={{ fontWeight: 700 }}>{loanQ.data.covenants}</div>
              </div>

              <div
                style={{
                  padding: 10,
                  borderRadius: 12,
                  border: "1px solid rgb(var(--border))",
                  background: "rgb(var(--bg))",
                }}
              >
                <div style={{ fontSize: 11, color: "rgb(var(--muted))" }}>ESG Clauses</div>
                <div style={{ fontWeight: 700 }}>{loanQ.data.esgClauses}</div>
              </div>
            </div>

            <div style={{ fontSize: 12, color: "rgb(var(--muted))", marginTop: 10 }}>
              Updated: {new Date(loanQ.data.lastUpdatedAt).toLocaleString()}
            </div>
          </>
        ) : null}
      </div>

      {/* Obligations */}
      {activeLoanId && (
        <div style={{ padding: "0 16px 16px 16px" }}>
          <div
            style={{
              borderRadius: "12px",
              border: "1px solid rgb(var(--border))",
              background: "rgb(var(--card))",
              padding: 12,
            }}
          >
            <div style={{ fontSize: "13px", fontWeight: 600, color: "rgb(var(--foreground))" }}>
              Obligations
            </div>
            <div style={{ marginTop: 4, fontSize: "12px", color: "rgb(var(--muted-foreground))" }}>
              Derived obligations are available in Servicing.
            </div>
            <div style={{ marginTop: 8 }}>
              <Link
                to={loanPaths.servicing(activeLoanId)}
                style={{
                  display: "inline-flex",
                  borderRadius: "8px",
                  border: "1px solid rgb(var(--border))",
                  padding: "6px 12px",
                  fontSize: "13px",
                  fontWeight: 500,
                  color: "rgb(var(--foreground))",
                  background: "rgb(var(--background))",
                  textDecoration: "none",
                  cursor: "pointer",
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.background = "rgb(var(--muted))";
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.background = "rgb(var(--background))";
                }}
              >
                Open Servicing
              </Link>
            </div>
          </div>
        </div>
      )}

      {/* Audit Timeline */}
      <div style={{ padding: "0 16px 16px 16px" }}>
        <div style={{ fontWeight: 600, marginBottom: 8 }}>{t("drawer.auditTimeline")}</div>

        {auditQ.isLoading ? (
          <div style={{ color: "rgb(var(--muted))" }}>Loading timeline…</div>
        ) : auditQ.isError ? (
          <div style={{ color: "rgb(var(--danger))" }}>Failed to load timeline</div>
        ) : auditQ.data ? (
          <ol style={{ margin: 0, paddingLeft: 18 }}>
            {auditQ.data.slice(0, 6).map((evt) => (
              <li key={evt.id} style={{ marginBottom: 10 }}>
                <div style={{ fontSize: 12, fontWeight: 600 }}>{evt.summary}</div>
                <div style={{ fontSize: 11, color: "rgb(var(--muted))" }}>
                  {new Date(evt.timestamp).toLocaleString()} • {evt.actor}
                  {evt.evidenceRef ? ` • ${evt.evidenceRef}` : ""}
                </div>
              </li>
            ))}
          </ol>
        ) : null}
      </div>

      {/* Actions */}
      <div style={{ marginTop: "auto", padding: 16, borderTop: "1px solid rgb(var(--border))" }}>
        <button
          onClick={() => {
            if (loanQ.data && activeLoanId) {
              exportLoanSummary(loanQ.data, auditQ.data || [], activeLoanId);
            }
          }}
          disabled={!loanQ.data || !activeLoanId || loanQ.isLoading}
          style={{
            width: "100%",
            padding: "10px 12px",
            borderRadius: 10,
            background: loanQ.data && activeLoanId ? "rgb(var(--primary))" : "rgb(var(--muted))",
            color: "white",
            border: "none",
            cursor: loanQ.data && activeLoanId ? "pointer" : "not-allowed",
            opacity: loanQ.data && activeLoanId ? 1 : 0.6,
            fontWeight: 500,
          }}
        >
          {t("drawer.actions.exportSummary")}
        </button>
      </div>
    </div>
  );
}
